### PR TITLE
update to jest v23

### PR DESCRIPTION
**Pull request by rufman**

### CODE REVIEW

**Comment by simon360** [comment]
@rufman thanks for this! Couple of minor things:
1. Since this doesn't break compatibility with Jest 22, would you mind setting the peerDependency range to `22.x || 23.x`?
2. I'll push out a release as soon as this is merged, but normally I'd do that with an `npm version minor` - would you mind reverting the change to the `version` field of `package.json`?

I hadn't realized that Jest 23 was out, glad you caught this! Is there a changelog anywhere?

**Comment by rufman** [comment]
@simon360 I force pushed an update.

Here is the changelog: https://github.com/facebook/jest/blob/master/CHANGELOG.md looks like what changed is the passing of the console via options to tests.

**Comment by simon360** [comment]
Excellent - thanks again!

**Comment by simon360** [comment]
@rufman published to npm as `1.1.0`

**Pull request merged**
